included:
  - LedgerPro/Sources
  - LedgerPro/Tests

excluded:
  - LedgerPro/.build
  - LedgerPro/Package.swift
  - LedgerPro/Sources/LedgerPro/Views/InsightsView.swift.backup

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - comment_spacing
  - computed_accessors_order
  - control_statement
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - force_cast
  - force_try
  - force_unwrapping
  - function_default_parameter_at_end
  - implicit_getter
  - joined_default_parameter
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - return_arrow_whitespace
  - shorthand_operator
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - unused_private_declaration
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - void_return
  - yoda_condition

disabled_rules:
  - todo
  - trailing_whitespace

# Custom rule configurations
force_unwrapping:
  severity: error
  
force_cast:
  severity: error
  
force_try:
  severity: warning

line_length:
  warning: 120
  error: 150

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 800

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 3
    error: 5
  statement_level:
    warning: 5
    error: 10

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - db
    - to
    - at
    - in
    - on
    - x
    - y

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60

# Custom rules for LedgerPro
custom_rules:
  no_direct_array_access:
    name: "No Direct Array Access"
    regex: '\[[0-9]+\]'
    match_kinds:
      - identifier
    message: "Use safe array access with subscript(safe:) instead of direct indexing"
    severity: warning
    
  no_unsafe_string_operations:
    name: "No Unsafe String Operations"
    regex: '\.prefix\([^)]*\)|\.suffix\([^)]*\)|\.dropFirst\([^)]*\)|\.dropLast\([^)]*\)'
    match_kinds:
      - identifier
    message: "Use safe string operations with bounds checking"
    severity: warning
    
  no_force_unwrap_in_services:
    name: "No Force Unwrap in Services"
    regex: '!'
    included: ".*/Services/.*\\.swift"
    match_kinds:
      - identifier
    message: "Force unwrapping is not allowed in Services directory"
    severity: error