name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  swift-tests:
    runs-on: macos-13  # Use macOS 13 runner
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode version
      run: |
        sudo xcode-select --switch /Applications/Xcode_15.0.app/Contents/Developer
        xcodebuild -version
        swift --version
    
    - name: Clean build
      run: |
        cd LedgerPro
        rm -rf .build
        rm -rf .swiftpm
    
    - name: Resolve dependencies
      run: |
        cd LedgerPro
        swift package resolve
    
    - name: Build Swift package
      run: |
        cd LedgerPro
        swift build --verbose
    
    - name: Run Swift tests
      run: |
        cd LedgerPro
        swift test --verbose

  python-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ghostscript libpoppler-cpp-dev python3-tk python3-dev
        sudo apt-get install -y libglib2.0-0 libsm6 libxext6 libxrender-dev libgomp1
    
    - name: Install Python dependencies
      run: |
        cd LedgerPro/backend
        python -m pip install --upgrade pip setuptools wheel
        pip install opencv-python-headless==4.8.0.74
        pip install -r requirements.txt
    
    - name: Run Python tests
      run: |
        cd LedgerPro/backend
        python -m pytest tests/ -v --tb=short
    
    - name: Run linting
      run: |
        cd LedgerPro/backend
        flake8 . --config=.flake8 --statistics
      continue-on-error: true