name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  swift-tests:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode version
      run: sudo xcode-select --switch /Applications/Xcode_15.2.app/Contents/Developer
    
    - name: Build Swift package
      run: |
        cd LedgerPro
        swift build
    
    - name: Run Swift tests
      run: |
        cd LedgerPro
        swift test
    
    - name: Check Swift formatting (if swiftformat available)
      run: |
        cd LedgerPro
        if command -v swiftformat >/dev/null 2>&1; then
          swiftformat --lint Sources/
        else
          echo "SwiftFormat not available, skipping format check"
        fi
      continue-on-error: true

  python-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ghostscript libpoppler-cpp-dev
    
    - name: Install Python dependencies
      run: |
        cd LedgerPro/backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Python linting
      run: |
        cd LedgerPro/backend
        flake8 . --exit-zero --statistics
      continue-on-error: true
    
    - name: Run Python tests
      run: |
        cd LedgerPro/backend
        pytest tests/ -v
    
    - name: Test Summary
      if: always()
      run: |
        echo "CI run complete. Check individual step results above."
EOF < /dev/null