name: Known Failing Tests

on:
  schedule:
    - cron: '0 12 * * *'  # Daily at noon
  workflow_dispatch:

jobs:
  track-failing-tests:
    name: Monitor Failing Tests
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run Known Failing Tests
      continue-on-error: true
      id: failing_tests
      run: |
        cd LedgerPro
        
        # Known failing tests that need attention
        echo "## Known Failing Tests Status" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        # Test 1: EndToEndCategorizationTest
        if swift test --filter "testComprehensiveEnhancedCategorization"; then
          echo "✅ EndToEndCategorizationTest: FIXED" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ EndToEndCategorizationTest: Still failing (confidence threshold)" >> $GITHUB_STEP_SUMMARY
        fi
        
        # Test 2: PatternLearningServiceEnhancedTests  
        if swift test --filter "testRuleSuggestion_afterThreshold_createsValidRule"; then
          echo "✅ PatternLearningServiceEnhancedTests: FIXED" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ PatternLearningServiceEnhancedTests: Still failing (rule suggestion)" >> $GITHUB_STEP_SUMMARY
        fi
        
    - name: Create Issue for Fixed Tests
      if: steps.failing_tests.outcome == 'success'
      uses: actions/github-script@v6
      with:
        script: |
          const title = '🎉 Previously failing tests are now passing';
          const body = `
          ## Tests Fixed!
          
          The following tests that were previously failing are now passing:
          - EndToEndCategorizationTest
          - PatternLearningServiceEnhancedTests
          
          These tests can now be included in the main CI pipeline.
          
          Auto-generated by GitHub Actions.
          `;
          
          await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: title,
            body: body,
            labels: ['good news', 'testing', 'automation']
          });

  test-isolation:
    name: Test in Isolation
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Test Core Functionality Only
      run: |
        cd LedgerPro
        
        # Run stable tests that should always pass
        swift test --filter "APIServiceTests|FinancialDataManagerTests|CriticalWorkflowTests|RangeErrorPinpointTest"
        
    - name: Performance Baseline
      run: |
        cd LedgerPro
        
        # Ensure performance tests still meet thresholds
        swift test --filter "testLargeDatasetWorkflow|testMemoryPerformanceWorkflow" > perf.txt
        
        echo "## Performance Baseline" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        grep -E "executed in|seconds\)" perf.txt >> $GITHUB_STEP_SUMMARY || true