name: Backend CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'LedgerPro/backend/**'
      - '.github/workflows/python-backend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'LedgerPro/backend/**'

jobs:
  test:
    name: Python Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        cd LedgerPro/backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov black flake8 mypy bandit
        
    - name: Lint with black
      run: |
        cd LedgerPro/backend
        black --check . || echo "Black formatting needed but not failing CI"
      continue-on-error: true
        
    - name: Lint with flake8
      run: |
        cd LedgerPro/backend
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        
    - name: Type check with mypy
      run: |
        cd LedgerPro/backend
        mypy . --ignore-missing-imports || true
        
    - name: Security check with bandit
      run: |
        cd LedgerPro/backend
        bandit -r . -ll || true
        
    - name: Run tests
      run: |
        cd LedgerPro/backend
        pytest -v --cov=. --cov-report=xml
        
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./LedgerPro/backend/coverage.xml
        flags: backend
