name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Release
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.0.app
    
    - name: Build Release
      run: |
        cd LedgerPro
        swift build -c release
        
    - name: Create Release Archive
      run: |
        cd LedgerPro/.build/release
        zip -r ../../LedgerPro-${{ github.ref_name }}.zip LedgerPro
        
    - name: Upload Release Asset
      uses: actions/upload-artifact@v3
      with:
        name: LedgerPro-${{ github.ref_name }}
        path: LedgerPro-${{ github.ref_name }}.zip
