name: Security & Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  dependency-check:
    name: Dependency Security
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Check Swift Dependencies
      run: |
        cd LedgerPro
        echo "### Swift Dependencies" >> $GITHUB_STEP_SUMMARY
        if [ -f "Package.resolved" ]; then
          echo "✅ Package.resolved found" >> $GITHUB_STEP_SUMMARY
        else
          echo "⚠️ No Package.resolved found" >> $GITHUB_STEP_SUMMARY
        fi

  memory-safety:
    name: Memory Safety
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build with Sanitizers
      run: |
        cd LedgerPro
        echo "### Memory Safety Build" >> $GITHUB_STEP_SUMMARY
        # Build with address sanitizer in debug mode
        swift build -c debug -Xswiftc -sanitize=address || echo "⚠️ Address sanitizer build failed" >> $GITHUB_STEP_SUMMARY
        echo "✅ Memory safety check completed" >> $GITHUB_STEP_SUMMARY
